availableSecrets:
    secretManager:
        - versionName: projects/$PROJECT_ID/secrets/serena-main-sql-connection/versions/latest
          env: "DATABASE_URL"
        - versionName: projects/$PROJECT_ID/secrets/spotify-client-id/versions/latest
          env: "SPOTIFY_CLIENT_ID"
        - versionName: projects/$PROJECT_ID/secrets/spotify-client-secret/versions/latest
          env: "SPOTIFY_CLIENT_SECRET"
        - versionName: projects/$PROJECT_ID/secrets/jwt-access-secret/versions/latest
          env: "JWT_ACCESS_SECRET"
images:
    - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
    substitutionOption: ALLOW_LOOSE
    logging: CLOUD_LOGGING_ONLY
substitutions:
    _SERVICE_NAME: serena-backend
    _TRIGGER_ID: d980f73f-fa5c-4dbd-8af6-ee9e67854f79
    _AR_HOSTNAME: asia-southeast2-docker.pkg.dev
    _DEPLOY_REGION: asia-southeast2
    _ENTRYPOINT: npm run start
    _PLATFORM: managed
tags:
    - gcp-cloud-build-deploy-cloud-run
    - gcp-cloud-build-deploy-cloud-run-managed
    - serena-backend
steps:
    - name: node:alpine
      entrypoint: npm
      args:
          - run
          - create-env
      secretEnv:
          - "DATABASE_URL"
          - "SPOTIFY_CLIENT_ID"
          - "SPOTIFY_CLIENT_SECRET"
          - "JWT_ACCESS_SECRET"
      env:
          - SERENA_EMOTION_DETECTOR_URL=https://serena-emotion-detector-2g6tjw7nja-et.a.run.app/
      id: GetEnv
    - name: gcr.io/k8s-skaffold/pack
      env:
          - GOOGLE_ENTRYPOINT=$_ENTRYPOINT
      args:
          - build
          - >-
              $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
          - "--builder=gcr.io/buildpacks/builder:v1"
          - "--network=cloudbuild"
          - "--path=."
          - "--env=GOOGLE_ENTRYPOINT"
      id: Buildpack
      entrypoint: pack
    - name: gcr.io/cloud-builders/docker
      args:
          - push
          - >-
              $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      id: Push
    - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
      args:
          - run
          - deploy
          - $_SERVICE_NAME
          - "--platform=managed"
          - >-
              --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
          - >-
              --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
          - "--region=$_DEPLOY_REGION"
          - "--quiet"
          - "--max-instances=1"
          - "--service-account=serena-backend@serena-777.iam.gserviceaccount.com"
          - "--allow-unauthenticated"
      id: Deploy
      entrypoint: gcloud
