steps:
    - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
      entrypoint: bash
      args:
          - "-c"
          - "npm run create-env --set-env-vars _DATABASE_URL=$$SECRET_DATABASE_URL"
      secretEnv:
          - "SECRET_DATABASE_URL"
    - name: node:18.16.0
      entrypoint: npm
      args:
          - run
          - create-env
      env:
          - DATABASE_URL=$_DATABASE_URL
      id: GetEnv
    - name: gcr.io/k8s-skaffold/pack
      env:
          - GOOGLE_ENTRYPOINT=$_ENTRYPOINT
      args:
          - build
          - >-
              $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
          - "--builder=gcr.io/buildpacks/builder:v1"
          - "--network=cloudbuild"
          - "--path=."
          - "--env=GOOGLE_ENTRYPOINT"
          - "--env=DATABASE_URL"
      id: Buildpack
      entrypoint: pack
    - name: gcr.io/cloud-builders/docker
      args:
          - push
          - >-
              $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      id: Push
    - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
      args:
          - run
          - services
          - update
          - $_SERVICE_NAME
          - "--platform=managed"
          - >-
              --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
          - >-
              --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
          - "--region=$_DEPLOY_REGION"
          - "--quiet"
      id: Deploy
      entrypoint: gcloud
availableSecrets:
    secretManager:
        - versionName: projects/$PROJECT_ID/secrets/serena-main-sql-connection/versions/latest
          env: "SECRET_DATABASE_URL"
images:
    - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
    substitutionOption: ALLOW_LOOSE
    logging: CLOUD_LOGGING_ONLY
substitutions:
    _SERVICE_NAME: serena-backend
    _TRIGGER_ID: d980f73f-fa5c-4dbd-8af6-ee9e67854f79
    _AR_HOSTNAME: asia-southeast2-docker.pkg.dev
    _DEPLOY_REGION: asia-southeast2
    _ENTRYPOINT: npm run start
    _PLATFORM: managed
tags:
    - gcp-cloud-build-deploy-cloud-run
    - gcp-cloud-build-deploy-cloud-run-managed
    - serena-backend
